// Compile the actual Windows popup bodies with a captured MessageBoxW call.
// This checks conditional C++ code and displayed values, not native GUI rendering.
#include <iostream>
#include <stdexcept>
#include <string>

constexpr unsigned MB_OK = 0;
constexpr unsigned MB_ICONINFORMATION = 0x40;
constexpr unsigned MB_ICONWARNING = 0x30;
constexpr unsigned MB_TOPMOST = 0x40000;
constexpr unsigned MB_SETFOREGROUND = 0x10000;
static std::wstring shownText, shownTitle;
static unsigned shownFlags = 0;
static int shownCount = 0;

int MessageBoxW(void*, const wchar_t* text, const wchar_t* title, unsigned flags) {
    shownText = text;
    shownTitle = title;
    shownFlags = flags;
    ++shownCount;
    return 1;
}

#ifndef _WIN32
#define _WIN32
#endif
// Generated by the runner from the unmodified struct and popup definitions.
#include "risk_dialogs_under_test.inc"

namespace {
void require(bool condition, const char* reason) {
    if (!condition) throw std::runtime_error(reason);
}
void contains(const std::wstring& value) {
    require(shownText.find(value) != std::wstring::npos, "Risk popup is missing a label or exact value");
}
void excludes(const std::wstring& value) {
    require(shownText.find(value) == std::wstring::npos, "Risk popup displays an incorrect mode label");
}
void checkCommonTrigger(bool selfTest) {
    contains(L"每日报备阈值：123 笔");
    contains(L"每秒报备阈值：7 笔／秒");
    contains(L"本次报单：已在本地拦截，未发送至柜台");
    contains(selfTest ? L"测试触发：是（未发送真实报单）" : L"测试触发：否");
    require(shownTitle.find(L"风控触发") != std::wstring::npos, "Wrong trigger popup title");
    require(shownFlags == (MB_OK | MB_ICONWARNING | MB_TOPMOST | MB_SETFOREGROUND),
            "Trigger popup lost warning or foreground flags");
}
}

int main() {
    try {
        showRiskSettingsDialog(123, 7);
        contains(L"每日最大报单量：123 笔");
        contains(L"每秒最大报单量：7 笔／秒");
        contains(L"配置项：daily_max_order_count");
        contains(L"配置项：per_second_max_order_count");
        contains(L"最近连续 1000 毫秒");
        require(shownTitle.find(L"风控设置") != std::wstring::npos, "Wrong settings popup title");
        require(shownFlags == (MB_OK | MB_ICONINFORMATION | MB_TOPMOST | MB_SETFOREGROUND),
                "Settings popup lost information or foreground flags");

        DailyOrderRiskDecision decision;
        decision.configuredLimit = 123;
        decision.perSecondLimit = 7;
        decision.submittedBefore = decision.submittedAfter = 123;
        decision.secondBefore = decision.secondAfter = 2;
        decision.peakPerSecond = 5;
        decision.blockedRule = "daily_max_order_count";
        showRiskTriggerDialog(decision, false);
        checkCommonTrigger(false);
        contains(L"风控触发：已达到每日最大报单量");
        contains(L"当日已计数：123 笔");
        contains(L"最近连续 1000 毫秒已计数：2 笔");
        contains(L"当日观察到的每秒峰值：5 笔／秒");
        excludes(L"自测窗口峰值");

        decision.submittedBefore = decision.submittedAfter = 11;
        decision.secondBefore = decision.secondAfter = 7;
        decision.peakPerSecond = 7;
        decision.blockedRule = "per_second_max_order_count";
        showRiskTriggerDialog(decision, false);
        checkCommonTrigger(false);
        contains(L"风控触发：已达到每秒最大报单量");
        contains(L"当日已计数：11 笔");
        contains(L"最近连续 1000 毫秒已计数：7 笔");
        contains(L"当日观察到的每秒峰值：7 笔／秒");
        excludes(L"自测窗口峰值");

        showRiskTriggerDialog(decision, true);
        checkCommonTrigger(true);
        contains(L"风控触发：已达到每秒最大报单量");
        contains(L"自测窗口峰值：7 笔／秒");
        excludes(L"当日观察到的每秒峰值");

        decision.blockedRule = "daily_max_order_count";
        decision.submittedBefore = decision.submittedAfter = 123;
        decision.secondBefore = decision.secondAfter = 0;
        decision.peakPerSecond = 0;
        showRiskTriggerDialog(decision, true);
        checkCommonTrigger(true);
        contains(L"风控触发：已达到每日最大报单量");
        contains(L"自测窗口峰值：0 笔／秒");
        excludes(L"当日观察到的每秒峰值");

        require(shownCount == 5, "Unexpected number of popup requests");
        std::cout << "PASS 5 Windows risk popup checks (captured MessageBoxW, not native rendering)\n";
        return 0;
    } catch (const std::exception& error) {
        std::cerr << "FAIL Windows risk popup checks: " << error.what() << '\n';
        return 1;
    }
}
